---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-app
  labels:
    type: learning
spec:
  selector:
    matchLabels:
      app: web
    replicas: 3
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
        - image: deontadams314/deon-repo:flask-python-app
          name: flask-web-app
          ports:
          - containerPort: 5050

